export const translations = {
  EN: {
    appTitle: 'AgroPulse AI',
    farmIntelligence: 'Farm Intelligence',
    analyzePrompt: "Tap 'Analyze' to get predictive crop profitability forecasting.",
    analyzeBtn: 'Analyze Season Profitability',
    voiceBtn: 'Voice AI Consultation',
    snapAnalyzeBtn: 'Crop Visual Diagnosis',
    scanning: 'Scanning Crop Features...',
    tickers: {
      onion: 'Lasalgaon Onion',
      cotton: 'Vidarbha Cotton',
      soybean: 'Latur Soybean',
    },
    regions: {
      andamanNicobar: 'Andaman & Nicobar',
      andhraPradesh: 'Andhra Pradesh',
      arunachalPradesh: 'Arunachal Pradesh',
      assam: 'Assam',
      bihar: 'Bihar',
      chandigarh: 'Chandigarh',
      chhattisgarh: 'Chhattisgarh',
      dadraNagarHaveli: 'Dadra & Nagar Haveli',
      delhi: 'Delhi',
      goa: 'Goa',
      gujarat: 'Gujarat',
      haryana: 'Haryana',
      himachalPradesh: 'Himachal Pradesh',
      jammuKashmir: 'Jammu & Kashmir',
      jharkhand: 'Jharkhand',
      karnataka: 'Karnataka',
      kerala: 'Kerala',
      ladakh: 'Ladakh',
      madhyaPradesh: 'Madhya Pradesh',
      maharashtra: 'Maharashtra',
      manipur: 'Manipur',
      meghalaya: 'Meghalaya',
      mizoram: 'Mizoram',
      nagaland: 'Nagaland',
      odisha: 'Odisha',
      puducherry: 'Puducherry',
      punjab: 'Punjab',
      rajasthan: 'Rajasthan',
      sikkim: 'Sikkim',
      tamilNadu: 'Tamil Nadu',
      telangana: 'Telangana',
      tripura: 'Tripura',
      uttarPradesh: 'Uttar Pradesh',
      uttarakhand: 'Uttarakhand',
      westBengal: 'West Bengal',
    },
    auth: {
      login: 'Login to AgroPulse',
      googleSignIn: 'Sign in with Google',
      email: 'Farmer Email / ID',
      password: 'Password',
      signIn: 'Sign In',
      onboardingWelcome: 'Welcome, {name}! Ready for your crop analysis?',
    },
    listening: 'Listening...',
    errors: {
      speechNotSupported: 'Speech recognition is not supported in this browser.',
      micDenied: 'Microphone access denied. Please enable permissions.',
      voiceFail: 'Consultation failed. Try again.',
      voiceError: 'Voice error:',
    },
  },
  HI: {
    appTitle: 'AgroPulse एआई',
    farmIntelligence: 'कृषि बुद्धिमत्ता',
    analyzePrompt: "फसल लाभप्रदता का अनुमान पाने के लिए 'विश्लेषण करें' पर टैप करें।",
    analyzeBtn: 'मौसम का लाभप्रदता विश्लेषण',
    voiceBtn: 'वॉयस एआई परामर्श',
    snapAnalyzeBtn: 'फसल दृश्य निदान',
    scanning: 'फसल सुविधाओं को स्कैन किया जा रहा है...',
    tickers: {
      onion: 'लासलगांव प्याज',
      cotton: 'विदर्भ कपास',
      soybean: 'लातूर सोयाबीन',
    },
    regions: {
      andamanNicobar: 'अंडमान और निकोबार',
      andhraPradesh: 'आंध्र प्रदेश',
      arunachalPradesh: 'अरुणाचल प्रदेश',
      assam: 'असम',
      bihar: 'बिहार',
      chandigarh: 'चंडीगढ़',
      chhattisgarh: 'छत्तीसगढ़',
      dadraNagarHaveli: 'दादरा और नगर हवेली',
      delhi: 'दिल्ली',
      goa: 'गोवा',
      gujarat: 'गुजरात',
      haryana: 'हरियाणा',
      himachalPradesh: 'हिमाचल प्रदेश',
      jammuKashmir: 'जम्मू और कश्मीर',
      jharkhand: 'झारखंड',
      karnataka: 'कर्नाटक',
      kerala: 'केरल',
      ladakh: 'लद्दाख',
      madhyaPradesh: 'मध्य प्रदेश',
      maharashtra: 'महाराष्ट्र',
      manipur: 'मणिपुर',
      meghalaya: 'मेघालय',
      mizoram: 'मिजोरम',
      nagaland: 'नागालैंड',
      odisha: 'ओडिशा',
      puducherry: 'पुदुचेरी',
      punjab: 'पंजाब',
      rajasthan: 'राजस्थान',
      sikkim: 'सिक्किम',
      tamilNadu: 'तमिलनाडु',
      telangana: 'तेलंगाना',
      tripura: 'त्रिपुरा',
      uttarPradesh: 'उत्तर प्रदेश',
      uttarakhand: 'उत्तराखंड',
      westBengal: 'पश्चिम बंगाल',
    },
    auth: {
      login: 'एग्रोपल्स में लॉगिन करें',
      googleSignIn: 'गूगल के साथ साइन इन करें',
      email: 'किसान ईमेल / आईडी',
      password: 'पासवर्ड',
      signIn: 'साइन इन करें',
      onboardingWelcome: 'स्वागत है, {name}! क्या आप अपने फसल विश्लेषण के लिए तैयार हैं?',
    },
    listening: 'सुन रहे हैं...',
    errors: {
      speechNotSupported: 'इस ब्राउज़र में स्पीच रिकग्निशन समर्थित नहीं है।',
      micDenied: 'माइक्रोफोन एक्सेस अस्वीकार कर दिया गया। कृपया अनुमतियां सक्षम करें।',
      voiceFail: 'परामर्श विफल रहा। पुनः प्रयास करें।',
      voiceError: 'वॉयस त्रुटि:',
    },
  },
  MR: {
    appTitle: 'अ‍ॅग्रोपल्स एआय',
    farmIntelligence: 'कृषी बुद्धिमत्ता',
    analyzePrompt: "पीक नफ्याचा अंदाज मिळवण्यासाठी 'विश्लेषण करा' वर टॅप करा.",
    analyzeBtn: 'हंगामी नफ्याचे विश्लेषण',
    voiceBtn: 'व्हॉईस एआय सल्ला',
    snapAnalyzeBtn: 'पीक दृश्य निदान',
    scanning: 'पीक वैशिष्ट्ये स्कॅन करत आहे...',
    tickers: {
      onion: 'लासलगाव कांदा',
      cotton: 'विदर्भ कापूस',
      soybean: 'लातूर सोयाबीन',
    },
    regions: {
      andamanNicobar: 'अंदमान आणि निकोबार',
      andhraPradesh: 'आंध्र प्रदेश',
      arunachalPradesh: 'अरुणाचल प्रदेश',
      assam: 'आसाम',
      bihar: 'बिहार',
      chandigarh: 'चंदीगड',
      chhattisgarh: 'छत्तीसगड',
      dadraNagarHaveli: 'दादरा आणि नगर हवेली',
      delhi: 'दिल्ली',
      goa: 'गोवा',
      gujarat: 'गुजरात',
      haryana: 'हरियाणा',
      himachalPradesh: 'हिमाचल प्रदेश',
      jammuKashmir: 'जम्मू आणि काश्मीर',
      jharkhand: 'झारखंड',
      karnataka: 'कर्नाटक',
      kerala: 'केरल',
      ladakh: 'लडाख',
      madhyaPradesh: 'मध्य प्रदेश',
      maharashtra: 'महाराष्ट्र',
      manipur: 'मणिपूर',
      meghalaya: 'मेघालय',
      mizoram: 'मिझोरम',
      nagaland: 'नागालँड',
      odisha: 'ओडिशा',
      puducherry: 'पुदुचेरी',
      punjab: 'पंजाब',
      rajasthan: 'राजस्थान',
      sikkim: 'सिक्किम',
      tamilNadu: 'तमिळनाडू',
      telangana: 'तेलंगणा',
      tripura: 'त्रिपुरा',
      uttarPradesh: 'उत्तर प्रदेश',
      uttarakhand: 'उत्तराखंड',
      westBengal: 'पश्चिम बंगाल',
    },
    auth: {
      login: 'अ‍ॅग्रोपल्समध्ये लॉगिन करा',
      googleSignIn: 'Google सह साइन इन करा',
      email: 'शेतकरी ईमेल / आयडी',
      password: 'पासवर्ड',
      signIn: 'साइन इन करा',
      onboardingWelcome: 'स्वागत आहे, {name}! तुमच्या पीक विश्लेषणासाठी तयार आहात का?',
    },
    listening: 'ऐकत आहे...',
    errors: {
      speechNotSupported: 'या ब्राउझरमध्ये स्पीच रिकग्निशन समर्थित नाही.',
      micDenied: 'मायक्रोफोन प्रवेश नाकारला. कृपया परवानग्या सक्षम करा.',
      voiceFail: 'सल्ला अयशस्वी. पुन्हा प्रयत्न करा.',
      voiceError: 'व्हॉईस त्रुटी:',
    },
  },
};
